name: cmmil
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.7.22=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.3=py39hdda0065_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jinja2=3.1.2=py39h06a4308_0
  # - jpeg=9b=0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.7.2.10=0
  - libcurand=10.3.3.141=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  # - libiconv=1.14=0
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.1.0=h2733197_1
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.0=h89dd481_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  # - mpc=1.0.3=0
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py39h06a4308_0
  - numpy=1.26.0=py39h5f9d8c6_0
  - numpy-base=1.26.0=py39hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.11=h7f8727e_2
  - pillow=9.3.0=py39hace64e9_1
  - pip=23.2.1=py39h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - pytorch=2.0.1=py3.9_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py39h06a4308_0
  - setuptools=68.0.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.11.1=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.0.2=py39_cu117
  - torchtriton=2.0.0=py39
  - torchvision=0.15.2=py39_cu117
  - typing_extensions=4.7.1=py39h06a4308_0
  - urllib3=1.26.16=py39h06a4308_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.4.9=haebb681_0
  - pip:
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.0
      - async-lru==2.0.4
      - attrs==23.1.0
      - babel==2.13.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - comm==0.1.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - exceptiongroup==1.1.3
      - executing==2.0.0
      - faiss-gpu==1.7.2
      - fastjsonschema==2.18.1
      - fonttools==4.43.1
      - fqdn==1.5.1
      - h5py==3.10.0
      - imageio==2.31.5
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - ipykernel==6.25.2
      - ipython==8.16.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.4.0
      - jupyter-core==5.4.0
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.7
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - nbclient==0.8.0
      - nbconvert==7.9.2
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - notebook-shim==0.2.3
      - opencv-python==4.8.1.78
      - openslide-python==1.3.0
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.1.1
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==3.11.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.16.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - referencing==0.30.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.6
      - scikit-image==0.22.0
      - scikit-learn==1.3.1
      - scipy==1.11.3
      - send2trash==1.8.2
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - terminado==0.17.1
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.11.2
      - types-python-dateutil==2.8.19.14
      - tzdata==2023.3
      - uri-template==1.3.0
      - wcwidth==0.2.8
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - zipp==3.17.0
prefix: /home/yhh/miniconda3/envs/cmmil
