DATASET:
  NAME: "TCGA_Glioma_S"  
  FEATURE_NAME: "features_clip_vit_b16"
  
TASK:
  NAME: "Survival" # 1. Grading  2. Subtyping 3. Survival 4. Classification
  LOSS: "nllsurvloss"

  
DATALOADER:
  TRAIN:
    BATCH_SIZE: 1
  TEST:
    BATCH_SIZE: 1
  NUM_WORKERS: 8


OPTIM:
  NAME: "adam"
  LR: 1e-5
  WEIGHT_DECAY: 1e-6
  STEPSIZE: [4000]
  MAX_EPOCH: 12
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 100

TEST:
  EVALUATOR: "Survival"

MODEL:
  FUSION:
    NAME: "hfb"

TRAINER:
  PREC: "fp32"