DATASET:
  NAME: "TCGA_Glioma_C"  
  FEATURE_NAME: "features_clip_vit_b16"
  
TASK:
  NAME: "Classification" # 1. Grading  2. Subtyping 3. Survival 4. Classification

DATALOADER:
  TRAIN:
    BATCH_SIZE: 1
  TEST:
    BATCH_SIZE: 1
  NUM_WORKERS: 8



OPTIM:
  NAME: "adam"
  LR: 2e-4
  WEIGHT_DECAY: 1e-5
  STEPSIZE: [4000]
  MAX_EPOCH: 20
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 2e-4

TRAIN:
  PRINT_FREQ: 100


MODEL:
  FUSION:
    NAME: "mcat"

TRAINER:
  PREC: "fp32"